# Install the project conda environment by running 
# the following command in your conda base environment:
# conda env create -f environment.yaml
name: '522'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - pip
  - ipykernel
  - nb_conda_kernels
  - altair=5.1.2
  - scipy
  - matplotlib>=3.2.2
  - scikit-learn>=1.3.1
  - requests>=2.24.0
  - graphviz
  - python-graphviz
  - eli5
  - shap
  - pip:
    - mglearn
    - psutil>=5.7.2
